# Python review

Short review about some core concepts in Python exemplified by objects in the Numpy library. 

Goals:

- recall basic Pythyon vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files. 

**NumPy:**

- core library for numberical computation in Python
- many libraries use Numpy arrays as their building blocks
- computations on Numpy objects are optimized for speed and memory usage

Let's import numpy with its **standard abbrviation np**

In [1]:
import numpy as np

(esc + press M twice -> convert code cell to markdown cell)

## Variables

**variable** a name is assign to a particular object in Python

Example:

In [2]:
# Assign a small array to variable a 
a = np.array([ [1,1,2], [3,5,8]])

To view a variable's valuye from our Jupyter notebook:

In [3]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
#Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use `snake case` for naming variables

This is the convention we will use in the course. Why? `my-variable` or `MyVariable` or `my_variable`
PEP 8 - Style guide for python code recommends snake_case. 

**Rememeber that variable names should beoth be descriptive and concise!**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific. 

Example:

Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specifice row or adding a new column. 

A variable is the name we give a specific object, and the same object can be reference by different variables. 

In practice, we can often use the word variable and object interchangeably.

## Types

Every object in Python has a type, the type tells us what kind of object it is. 
We can also call the type of an object, the **class** of an object, so class and type both mean what kind of object we have.

In [5]:
print(a)
type(a)

#We can see the type/class of a variable/object by using the type function:

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The numpy.ndarray is the core object/data type in the NumPy package. We can check the type of an entry in the array by indexing:

In [6]:
print(a[0,0])

type(a[0,0])

1


numpy.int64

`numpy.int64` and not just the standard Python integer type `int`. 

The NumPy type `numpy.int64` is telling us 1 is an integer stored as a 64-bit number. 

How would you access the value 5 in the array a? `a[1,1]``

In [7]:
a[1,1]

5

## Functions

`print` was our first example of a Python **function**. 

Functions take in a set of arguments, separated by commas, and use those arguments to create an **output**.

There are several built-in funcions in Python, most of them are for interacting with the Python basic data types such as int (integers), float (decimal numbers), str (strings), and bool (boolean values).

In this course we will use argument and parameter interchangeably. They do, however, have related but different meanings.

We can ask for information about what a function does function by executing ? followed by the function name:

In [8]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring**, a special type of comment that is used to document how a function (or class, or module) works.

You can see there are different types of arguments inside the parenthesis. Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments you need to specify for the function to do something, and
- **optional arguments**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`.

## Example

`end` is a parameter in print with the default value a new line. We can pass the value ``^_^` to this parameter so that finishes the line with ``^_^`` instead:

In [10]:
print('changing the default end argument of the print function', end=' ^_^')

changing the default end argument of the print function ^_^

## Attributes & methods

An object in Python has attributes and methods. 

- **attribute** is a property of the object, some piece of information about it. 
- **method** is a procedure associated with an object, so it is an action where the main ingredient is the object.

Example:
NumPy arrays have many methods and attributes. Let’s see some concrete examples.

In [11]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [12]:
print(a.T)
print(type(a.T))

[[1 3]
 [1 5]
 [2 8]]
<class 'numpy.ndarray'>


In [13]:
type(a.T)

numpy.ndarray

In [14]:
#shape, another attribute, tells us the shape of the array:

print(a.shape)

(2, 3)


In [15]:
print(type(a.shape))

<class 'tuple'>


In [16]:
#ndim  is an attribute holding the number of array dimensions
print('dim', a.ndim, '| type:', type(a.ndim))

dim 2 | type: <class 'int'>


Attributes can have many different data types. 

Some examples of methods:

In [17]:
#The min method returns the minimum value in the array along a specified axis:
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [18]:
#run min method with axis
a.min()

1

Remember, methods are functions associated to an object. We can confirm this!

In [19]:
# method tolist() transform array to list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [20]:
type(a.tolist)

builtin_function_or_method

In [21]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


sep:   string inserted between values, default a space. 

In [25]:
f = 77
g_string = '99'

In [26]:
print(f, g_string, f, sep = '%')

77%99%77
