# Python review

Short review about some core concepts in Python exemplified by objects in the Numpy library. 

Goals:

- recall basic Pythyon vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files. 

**NumPy:**

- core library for numberical computation in Python
- many libraries use Numpy arrays as their building blocks
- computations on Numpy objects are optimized for speed and memory usage

Let's import numpy with its **standard abbrviation np**

In [1]:
import numpy as np

(esc + press M twice -> convert code cell to markdown cell)

## Variables

**variable** a name is assign to a particular object in Python

Example:

In [2]:
# Assign a small array to variable a 
a = np.array([ [1,1,2], [3,5,8]])

To view a variable's valuye from our Jupyter notebook:

In [3]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
#Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]
